language: go

script:
    - go vet ./...
    - go test -v ./...
arch:
  - AMD64
  - ppc64le
go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip
# Disable version 1.3, 1.4
jobs: 
  exclude:
    - arch: ppc64le
      go: 1.3
    - arch: ppc64le
      go: 1.4
